// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/posts/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/posts/client.go -destination=internal/pkg/posts/client_mock.go -package=posts
//

// Package posts is a generated GoMock package.
package posts

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostsClient is a mock of PostsClient interface.
type MockPostsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostsClientMockRecorder
	isgomock struct{}
}

// MockPostsClientMockRecorder is the mock recorder for MockPostsClient.
type MockPostsClientMockRecorder struct {
	mock *MockPostsClient
}

// NewMockPostsClient creates a new mock instance.
func NewMockPostsClient(ctrl *gomock.Controller) *MockPostsClient {
	mock := &MockPostsClient{ctrl: ctrl}
	mock.recorder = &MockPostsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostsClient) EXPECT() *MockPostsClientMockRecorder {
	return m.recorder
}

// GetPosts mocks base method.
func (m *MockPostsClient) GetPosts(ctx context.Context, userID string) ([]Post, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx, userID)
	ret0, _ := ret[0].([]Post)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockPostsClientMockRecorder) GetPosts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockPostsClient)(nil).GetPosts), ctx, userID)
}
