// Code generated by generator; DO NOT EDIT.
package config

func (c *Config) StructToMap() map[string]interface{} {
    return map[string]interface{}{
        /* Tag: `yaml:"name" json:"app_name"` */
        "AppName": c.AppName,
        /* Tag: `yaml:"version" json:"version"` */
        "Version": c.Version,
        /* Tag: `yaml:"timeout" json:"timeout"` */
        "Timeout": c.Timeout,
        /* Tag: `yaml:"database" json:"database"` */
        "Database": c.Database,
        /* Tag: `yaml:"monitoring" json:"monitoring"` */
        "Monitoring": c.Monitoring,
        /* Tag: `yaml:"cache" json:"cache"` */
        "Cache": c.Cache,
    }
}
